### PR TITLE
Test WAC-Allow header

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
+import fetch from 'node-fetch';

**Comment by michielbdejong** [comment]
This does pass:

```js
it(`Shows the correct WAC-Allow header on Alice's public folder`, async () => {
    const result = await solidLogicBob.fetch(`https://server/public/`);
    expect(result.headers.get('WAC-Allow')).toEqual('user="read",public="read"');
});
```

**Comment by edwardsph** [comment]
I'm not sure I got the process write for offering a PR on top of a request to review a PR - please let me know if there was a better way to do this.

**Comment by michielbdejong** [comment]
Merged your PR into mine, if you approve this one, then i will merge it.

**Review by edwardsph — APPROVED** [review]
LGTM

**Pull request merged**
